### PR TITLE
add option: `cacheUntilRejected`

### PR DESCRIPTION
**Pull request by nitsanavni**

### CODE REVIEW

**Comment by PierreDuc** [comment]
@nitsanavni Thanks for your pull request! Could you add some documentation to the API readme as well, to explain what this option specifically does?

**Comment by nitsanavni** [comment]
@PierreDuc sure, np

**Comment by nitsanavni** [comment]
@PierreDuc done

**Comment by nitsanavni** [comment]
@PierreDuc thanks!

**Pull request merged**
